-- Comprehensive test schema using all newly-added DDL features
-- Tests: CREATE TYPE AS ENUM, CHECK constraints, GENERATED AS IDENTITY, CREATE VIEW, ALTER TABLE

-- ============================================
-- ENUM Types
-- ============================================
CREATE TYPE user_role AS ENUM ('admin', 'editor', 'viewer', 'guest');
CREATE TYPE order_status AS ENUM ('pending', 'confirmed', 'shipped', 'delivered', 'cancelled');
CREATE TYPE priority_level AS ENUM ('low', 'medium', 'high', 'critical');

-- ============================================
-- Tables with CHECK constraints and IDENTITY columns
-- ============================================
CREATE TABLE users (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    role user_role NOT NULL DEFAULT 'viewer',
    age INTEGER CHECK (age >= 0 AND age <= 150),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,
    parent_id INTEGER,
    sort_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT slug_format CHECK (slug ~ '^[a-z0-9-]+$'),
    CONSTRAINT sort_order_positive CHECK (sort_order >= 0)
);

CREATE TABLE products (
    id SERIAL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    stock_quantity INTEGER NOT NULL DEFAULT 0,
    category_id INTEGER NOT NULL,
    is_available BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT price_positive CHECK (price > 0),
    CONSTRAINT stock_non_negative CHECK (stock_quantity >= 0),
    FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE orders (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    status order_status NOT NULL DEFAULT 'pending',
    total_amount DECIMAL(12, 2) NOT NULL,
    priority priority_level NOT NULL DEFAULT 'medium',
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT total_positive CHECK (total_amount >= 0),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE order_items (
    id SERIAL PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price DECIMAL(10, 2) NOT NULL,
    CONSTRAINT quantity_positive CHECK (quantity > 0),
    CONSTRAINT unit_price_positive CHECK (unit_price > 0),
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (product_id) REFERENCES products(id)
);

-- ============================================
-- VIEWs
-- ============================================
CREATE VIEW active_users AS
    SELECT id, username, email, role, created_at
    FROM users
    WHERE is_active = true;

CREATE VIEW product_catalog AS
    SELECT p.id, p.name, p.description, p.price, p.stock_quantity,
           c.name AS category_name, c.slug AS category_slug
    FROM products p
    JOIN categories c ON p.category_id = c.id
    WHERE p.is_available = true;

CREATE VIEW order_summary AS
    SELECT o.id AS order_id, u.username, u.email,
           o.status, o.total_amount, o.priority, o.created_at
    FROM orders o
    JOIN users u ON o.user_id = u.id;

CREATE VIEW order_details AS
    SELECT oi.id, oi.order_id, p.name AS product_name,
           oi.quantity, oi.unit_price,
           (oi.quantity * oi.unit_price) AS line_total
    FROM order_items oi
    JOIN products p ON oi.product_id = p.id;

-- Wildcard VIEW (tests * expansion)
CREATE VIEW all_orders AS
    SELECT * FROM orders;

-- ============================================
-- ALTER TABLE
-- ============================================
ALTER TABLE users ADD COLUMN phone VARCHAR(20);
ALTER TABLE users ADD COLUMN last_login TIMESTAMP;

ALTER TABLE products ADD COLUMN weight DECIMAL(8, 2);
ALTER TABLE products ADD COLUMN sku VARCHAR(50) UNIQUE;

ALTER TABLE orders ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE categories RENAME COLUMN sort_order TO display_order;
